/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.sbapr.gui.DataSourcePanels;

import cz.muni.fi.sbapr.utils.IterableNodeList;
import cz.muni.fi.sbapr.utils.RGHelper;
import java.awt.Dialog;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

/**
 *
 * @author Adam
 */
public class TextDataSourcePanel extends DataSourcePanel {

    /**
     * Creates new form IMGDataSourcePanel
     *
     * @param parent
     */
    public TextDataSourcePanel(Dialog parent) {
        super(parent);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textPanel = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setMinimumSize(new java.awt.Dimension(300, 150));
        setPreferredSize(new java.awt.Dimension(300, 300));

        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textPanel.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(textPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(textPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     * @param element
     * @return
     */
    @Override
    public boolean updateElement(Element element) {
        new IterableNodeList(element.getChildNodes()).forEach(child -> element.removeChild(child));

        Document doc = RGHelper.INSTANCE.getDoc();
        Element textElement = doc.createElement("text");
        textElement.appendChild(doc.createTextNode(textArea.getText()));

        element.appendChild(textElement);
        return true;

    }

    /**
     *
     * @param element
     */
    @Override
    public void loadElement(Element element) {
        textArea.setText(getAttribute(element, "text") == null ? "" : getAttribute(element, "text"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea textArea;
    private javax.swing.JScrollPane textPanel;
    // End of variables declaration//GEN-END:variables
}
